### ISSUE TITLE
Cannot build with esp-idf 4.4

### ISSUE THREAD

**Issue by utement** [atanisoft/Esp32OlcbIO#11]
I cant build firmware with esp-idf 4.4. Looks like dependencies don't match.

`
bash-5.2$ idf.py menuconfig
Executing action: menuconfig
Running ninja in directory /Users/utement/Projects/esp/Esp32OlcbIO/firmware/build
Executing "ninja menuconfig"...
[0/1] cd /Users/utement/Projects/esp/Esp32OlcbIO/firmware/build && /Users/utement/.espressif/python_env/idf5....F_TARGET=esp32 --env IDF_ENV_FPGA= --output config /Users/utement/Projects/esp/Esp32OlcbIO/firmware/sdkconfig
Loading defaults file /Users/utement/Projects/esp/Esp32OlcbIO/firmware/sdkconfig.defaults...
/Users/utement/Projects/esp/Esp32OlcbIO/firmware/sdkconfig.defaults:102 CONFIG_ESP_TASK_WDT was replaced with CONFIG_ESP_TASK_WDT_INIT
TERM environment variable is set to "xterm-256color"
/Users/utement/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages/menuconfig.py: /Users/utement/Projects/esp/esp-idf-5.0/components/esp_psram/./esp32/Kconfig.spiram:62: '/Users/utement/Projects/esp/esp-idf-4.4/components/esp_psram/Kconfig.spiram.common' not found (in 'source "$IDF_PATH/components/esp_psram/Kconfig.spiram.common"    # insert non-chip-specific items here'). Check that environment variables are set correctly (e.g. $srctree, which is unset or blank). Also note that unset environment variables expand to the empty string.
FAILED: CMakeFiles/menuconfig /Users/utement/Projects/esp/Esp32OlcbIO/firmware/build/CMakeFiles/menuconfig
cd /Users/utement/Projects/esp/Esp32OlcbIO/firmware/build && /Users/utement/.espressif/python_env/idf5.0_py3.10_env/bin/python /Users/utement/Projects/esp/esp-idf-5.0/tools/kconfig_new/prepare_kconfig_files.py --list-separator=semicolon --env-file /Users/utement/Projects/esp/Esp32OlcbIO/firmware/build/config.env && /Users/utement/.espressif/python_env/idf5.0_py3.10_env/bin/python /Users/utement/Projects/esp/esp-idf-5.0/tools/kconfig_new/confgen.py --list-separator=semicolon --kconfig /Users/utement/Projects/esp/esp-idf-5.0/Kconfig --sdkconfig-rename /Users/utement/Projects/esp/esp-idf-5.0/sdkconfig.rename --config /Users/utement/Projects/esp/Esp32OlcbIO/firmware/sdkconfig --defaults /Users/utement/Projects/esp/Esp32OlcbIO/firmware/sdkconfig.defaults --env-file /Users/utement/Projects/esp/Esp32OlcbIO/firmware/build/config.env --env IDF_TARGET=esp32 --env IDF_ENV_FPGA= --dont-write-deprecated --output config /Users/utement/Projects/esp/Esp32OlcbIO/firmware/sdkconfig && /Users/utement/.espressif/python_env/idf5.0_py3.10_env/bin/python /Users/utement/Projects/esp/esp-idf-5.0/tools/check_term.py && /opt/local/bin/cmake -E env COMPONENT_KCONFIGS_SOURCE_FILE=/Users/utement/Projects/esp/Esp32OlcbIO/firmware/build/kconfigs.in COMPONENT_KCONFIGS_PROJBUILD_SOURCE_FILE=/Users/utement/Projects/esp/Esp32OlcbIO/firmware/build/kconfigs_projbuild.in KCONFIG_CONFIG=/Users/utement/Projects/esp/Esp32OlcbIO/firmware/sdkconfig IDF_TARGET=esp32 IDF_ENV_FPGA= /Users/utement/.espressif/python_env/idf5.0_py3.10_env/bin/python -m menuconfig /Users/utement/Projects/esp/esp-idf-5.0/Kconfig && /Users/utement/.espressif/python_env/idf5.0_py3.10_env/bin/python /Users/utement/Projects/esp/esp-idf-5.0/tools/kconfig_new/confgen.py --list-separator=semicolon --kconfig /Users/utement/Projects/esp/esp-idf-5.0/Kconfig --sdkconfig-rename /Users/utement/Projects/esp/esp-idf-5.0/sdkconfig.rename --config /Users/utement/Projects/esp/Esp32OlcbIO/firmware/sdkconfig --defaults /Users/utement/Projects/esp/Esp32OlcbIO/firmware/sdkconfig.defaults --env-file /Users/utement/Projects/esp/Esp32OlcbIO/firmware/build/config.env --env IDF_TARGET=esp32 --env IDF_ENV_FPGA= --output config /Users/utement/Projects/esp/Esp32OlcbIO/firmware/sdkconfig
ninja: build stopped: subcommand failed.
ninja failed with exit code 1
bash-5.2$ idf.py menuconfig
Executing action: menuconfig
Running ninja in directory /Users/utement/Projects/esp/Esp32OlcbIO/firmware/build
Executing "ninja menuconfig"...
[0/1] Re-running CMake...
-- Building ESP-IDF components for target esp32
Solving dependencies requirements
Skipping optional dependency: espressif/mdns
.................................CMake Error at /Users/utement/Projects/esp/esp-idf-4.4/tools/cmake/build.cmake:463 (message):
  HINT: Please check manifest file of the following component(s): main

  ERROR: Because project depends on idf (>=5.0) which doesn't match any
  versions, version solving failed.

Call Stack (most recent call first):
  /Users/utement/Projects/esp/esp-idf-4.4/tools/cmake/project.cmake:476 (idf_build_process)
  CMakeLists.txt:7 (project)

-- Configuring incomplete, errors occurred!
See also "/Users/utement/Projects/esp/Esp32OlcbIO/firmware/build/CMakeFiles/CMakeOutput.log".
FAILED: build.ninja
/opt/local/bin/cmake --regenerate-during-build -S/Users/utement/Projects/esp/Esp32OlcbIO/firmware -B/Users/utement/Projects/esp/Esp32OlcbIO/firmware/build
ninja: error: rebuilding 'build.ninja': subcommand failed
ninja failed with exit code 1
bash-5.2$ idf.py build
Executing action: all (aliases: build)
Running ninja in directory /Users/utement/Projects/esp/Esp32OlcbIO/firmware/build
Executing "ninja all"...
[0/1] Re-running CMake...
-- Building ESP-IDF components for target esp32
Solving dependencies requirements
Skipping optional dependency: espressif/mdns
.................................CMake Error at /Users/utement/Projects/esp/esp-idf-4.4/tools/cmake/build.cmake:463 (message):
  HINT: Please check manifest file of the following component(s): main

  ERROR: Because project depends on idf (>=5.0) which doesn't match any
  versions, version solving failed.

Call Stack (most recent call first):
  /Users/utement/Projects/esp/esp-idf-4.4/tools/cmake/project.cmake:476 (idf_build_process)
  CMakeLists.txt:7 (project)

-- Configuring incomplete, errors occurred!
See also "/Users/utement/Projects/esp/Esp32OlcbIO/firmware/build/CMakeFiles/CMakeOutput.log".
FAILED: build.ninja
/opt/local/bin/cmake --regenerate-during-build -S/Users/utement/Projects/esp/Esp32OlcbIO/firmware -B/Users/utement/Projects/esp/Esp32OlcbIO/firmware/build
ninja: error: rebuilding 'build.ninja': subcommand failed
ninja failed with exit code 1
`

**Comment by atanisoft** [comment]
ESP-IDF v4.x is no longer supported, please use ESP-IDF v5.1.2.

**Comment by utement** [comment]
I tried with esp-idf 5.2 and 5.1.2, but I wasn't able to build. So after reading documentation I trided 4.4, again I wasnt able to build it. After your suggestion and complete reinstall of 5.1.2 it worked. I'm not sure but looks like I had broken install or something.

Please update documentation. Currently it says: The ESP32 OpenLCB IO Board depends on ESP-IDF v4.4.x and will not build with ESP-IDF v5.0.x at this time.

This issue can be closed now.

**Comment by atanisoft** [comment]
Ahh, I missed that it had embedded notes for IDF v4.4 in the firmware tree. I've updated the notes (see commit link below), I haven't tested with IDF v5.2 or master at this time though. Once we have a stable IDF v5.2 I'll be reviewing that for updates.
