### ISSUE TITLE
Error during compiling esp32io_bootloader.cpp

### ISSUE THREAD

**Issue by dwightkelly** [atanisoft/Esp32OlcbIO#7]
a clean clone of the master branch has the compiler error:
```
In file included from ../main/esp32io_bootloader.cpp:39:
../components/OpenMRNIDF/src/freertos_drivers/esp32/Esp32BootloaderHal.hxx: In function 'void esp32_bootloader_run(uint64_t, gpio_num_t, gpio_num_t, bool)':
../components/OpenMRNIDF/src/freertos_drivers/esp32/Esp32BootloaderHal.hxx:354:12: error: enumeration value 'CHIP_ESP32H2' not handled in switch [-Werror=switch]
     switch (chip_info.model)
            ^
```

This enum value was added on 1/7/22 in [0f6073123ebb836d6515858a56661fb36ddd23e5](https://github.com/atanisoft/OpenMRNIDF/commit/0f6073123ebb836d6515858a56661fb36ddd23e5)

The servo branch is using newer version (9/18/22)  [10b7e3cf3c65cf0e71788427e6c3227b100f4802](https://github.com/atanisoft/OpenMRNIDF/commit/10b7e3cf3c65cf0e71788427e6c3227b100f4802)

**Comment by atanisoft** [comment]
Master should be pointing to [217a5db2465b9091a106ce9ca476a6f37ec6f4dd](https://github.com/atanisoft/OpenMRNIDF/tree/217a5db2465b9091a106ce9ca476a6f37ec6f4dd) which has no reference to `CHIP_ESP32H2` that I can find.
.
This will be resolved on the `servo` branch which syncs to the latest OpenMRNIDF and switches to ESP-IDF v4.4 (master uses v4.3)

**Comment by dwightkelly** [comment]
I must have somehow forced OpenMRNIDF to HEAD.
